# Custom Resource
dboo:
  admin:
    password: ${DBOO_PASSWORD:password}

# SERVER
server:
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  shutdown: graceful

# Spring
spring:
  profiles:
    active: ${PROFILE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:db}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
#    hikari:
#      maximum-pool-size: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# LOGGING
logging:
  charset:
    console: UTF-8
    file: UTF-8
  config: classpath:log4j2.xml
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: deploy
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
  config: classpath:log4j2-deploy.xml
