spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:db}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
#    hikari:
#      maximum-pool-size: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:db}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

