name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{secrets.REGISTRY_HOST}}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build
        
    - name: Build the Docker image
      run: docker build . -t ${{secrets.REGISTRY_HOST}}/dboo:$(date +%s)

    - name: Login to Private Docker Registry
      uses: docker/login-action@v1
      with:
        registry: $${{secrets.REGISTRY_HOST}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Register private registry host to docker daemon
    #   run: echo "{ "insecure-registries": ["$HOST"] }" > /etc/docker/daemon.json

    # - name: docker login
    #   run: docker login ${{secrets.REGISTRY_HOST}} -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
      
    - name: docker push image
      run: docker push ${{secrets.REGISTRY_HOST}}/dboo:latest
