name: Continuous Integration and Delivery

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY_HOST }}
      KEY: ${{ secrets.SSH_KEY }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build
        
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.REGISTRY_HOST }}/dboo:latest

    - name: Register private registry host to docker daemon
      run: |  
        echo '#!/bin/bash' > login.sh
        echo 'echo "{ \"insecure-registries\" : [\"$REGISTRY\"] }" | sudo tee /etc/docker/daemon.json' >> login.sh
        echo 'sudo systemctl restart docker' >> login.sh
        chmod +x login.sh
        bash login.sh

    - name: Login private docker registry
      run: docker login ${{secrets.REGISTRY_HOST}} -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
      
    - name: Push docker image
      run: docker push ${{ secrets.REGISTRY_HOST }}/dboo:latest
      
    - name: Rollout Deployment
      run: |
        echo \"$KEY\" > id_rsa
        chmod 600 id_rsa
        ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "kubectl rollout restart dboo-spring -n dboo"
