name: Continuous Integration and Delivery

on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY_HOST }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build
        
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.REGISTRY_HOST }}/dboo:latest

    - name: Register Private Registry to Docker Daemon
      run: |  
        echo '#!/bin/bash' > login.sh
        echo 'echo "{ \"insecure-registries\" : [\"$REGISTRY\"] }" | sudo tee /etc/docker/daemon.json' >> login.sh
        echo 'sudo systemctl restart docker' >> login.sh
        chmod +x login.sh
        bash login.sh

    - name: Login Private Registry
      run: docker login ${{secrets.REGISTRY_HOST}} -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
      
    - name: Push Docker image
      run: docker push ${{ secrets.REGISTRY_HOST }}/dboo:latest

    - name: Remove login.sh && daemon.json
      run: rm -f login.sh && sudo rm -f /etc/docker/daemon.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Rollout Deployment
      # You may pin to the exact commit or the version.
      # uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: kubectl rollout restart deploy dboo-spring -n dboo
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        pass: ${{ secrets.SSH_PASSWORD }}
